// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
import { createCard, renderWith } from "obix-core-component";
export { createCard } from "obix-core-component";
export type { CardConfig, CardImage, CardState } from "obix-core-component";
export const renderCard = renderWith(createCard);
